### ISSUE TITLE
add Meta-data information to about the API on the cards

### ISSUE THREAD

**Issue by azbarcea** [APIs-guru/APIs-guru.github.io#11]
Any software is actually the service that it presents, which in turn exposes an API. So you could say that the software has the following version numbers:
* _Package Version_
* _Software Version_ (implementation version)
* API version or _Software Specification_ version

Some APIs are public (that what you find on the https://apis.guru), some are private (you might not know the software version). But I think the cards should get more inspired from the ([_infobox_-es from Wikipedia](https://en.wikipedia.org/w/index.php?title=Template:Infobox_software&action=edit) and show all the information that is already in the json, like:
- license
- support info
- active/not
- software version (if known-ed)
- etc

**Comment by MikeRalphson** [comment]
Closing as this is very old - information such as the API license and contact information will now be visible through the ReDoc link for each API.
