### ISSUE TITLE
Add API dialog, add categories and logo URL

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/APIs-guru.github.io#12]
Could you add a 'suggested categories' input to your Add API form, maybe even linked to [resources/categories](https://raw.githubusercontent.com/APIs-guru/openapi-directory/master/resources/categories.yaml) ? This will help me remember to add categories to new APIs.

A logo URL field would also be useful.

**Comment by RomanGotsiy** [comment]
@MikeRalphson sure. Will do it ASAP.

**Comment by MikeRalphson** [comment]
Thanks, no rush.

**Comment by MikeRalphson** [comment]
Website updated via #20
