### ISSUE TITLE
Metrics on front page should be automatically updated.

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/APIs-guru.github.io#5]
Right now metrics are updated by hand directly in HTML.
You can get  umber of APIs/Endpoints from here:
https://api.apis.guru/v2/metrics.json

**Comment by IvanGoncharov** [comment]
+ it makes sense to display some of the metrics on https://apis.guru/browse-apis/

**Comment by azbarcea** [comment]
should it be something like _Github Pulse_? Would _Github Pulse_ for `openapi-directory` be enough?

**Comment by IvanGoncharov** [comment]
I meant this counters on the front page:
![image](https://cloud.githubusercontent.com/assets/8336157/19401354/9c156eb6-9263-11e6-9688-a6f6f38c3e70.png)

Currently, they specified directly in HTML:
https://github.com/APIs-guru/APIs-guru.github.io/blob/source/src/index.html#L31-L59
It would be great to keep them in sync:
  - get number of stars from GitHub
  - number of APIs/endpoints from here: https://api.apis.guru/v2/metrics.json
