### ISSUE TITLE
Add button to sort APIs by added timestamp

### ISSUE THREAD

**Issue by IvanGoncharov** [APIs-guru/APIs-guru.github.io#9]
`list.json` already has `added` timestamps for every API

**Comment by azbarcea** [comment]
do you envision something like isotope: http://isotope.metafizzy.co/ ?

**Comment by IvanGoncharov** [comment]
@azbarcea Animations looks cool but I have close to zero knowledge of front-end.
@RomanGotsiy what do you think?

\+ My 5 cents if we will use such library it should have capabilities to handle all sorting criteria we want to introduce in the near future:
  - Search based on `description` from Swagger
  - Group APIs based on `x-providerName` to group all Google, Azure, NY Times, etc. Here is [example from Azure APIs](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/arm-cdn/2016-04-02/swagger.yaml#L19)
  - Sorted by `added` timestamp
  - Group by [categories](https://github.com/APIs-guru/openapi-directory/blob/master/resources/categories.yaml)
  - Search based on `x-keywords` field.

**Comment by azbarcea** [comment]
In order to apply sorting, the rendering should be done over an array, and not Object. This can be done either in UI, or UI+api (preferred).

**Comment by IvanGoncharov** [comment]
@azbarcea I agree most APIs return the result in an array as a container for elements (usually, to implement pagination). So in `v3` I will also use an array as the container to not confuse developers and provide easier integration with 3rd-party tools.

Meanwhile, I think it very easy to convert an object into an array with a few lines of JS code. And since JS use references such conversion should be blazingly fast and have tiny memory footprint.

**Comment by RomanGotsiy** [comment]
@IvanGoncharov, @azbarcea isotope looks awesome 👍 
Would be great if you can integrate this for sorting. Don't worry about difficult usecases Ivan mentioned :) Simple sorting by timestamp would be already a big improvement and a good first step

**Comment by azbarcea** [comment]
The biggest concern regarding `isotope` is its license: http://isotope.metafizzy.co/license.html

The best alternative options:
* **crossfilter** - https://square.github.io/crossfilter/ (uses d3js) - Apache 2.0
* **quicksand** - https://razorjack.net/quicksand/ - dual MIT and GPL3

The quickest implementation would be using quicksand, but the correct implementation would be using crossfilter, because would imply to standard the data model, later on you can add those statistics as nice d3 infographics as well.

Btw, I notice that an `end-of-life` field would also be helpful. I have no idea how that one could be maintained.

**Comment by IvanGoncharov** [comment]
> The biggest concern regarding isotope is its license: http://isotope.metafizzy.co/license.html

Yes, it's sad 😢 

> The quickest implementation would be using quicksand, but the correct implementation would be using crossfilter, because would imply to standard the data model, later on you can add those statistics as nice d3 infographics as well.

From [this example](https://razorjack.net/quicksand/demos/one-set-clone.html) it's looks like `quicksand` doesn't handle sorting/filtering and used only to refresh DOM and draw animation.
So it should be compatible with `crossfilter` which is only responsible for filtering data(d3js used only in the demo).

> Crossfilter supports extremely fast (<30ms) interaction with coordinated views, even with datasets **containing a million or more records**.

IMHO, it's an overkill for the collection of 300+ objects.

**Comment by RomanGotsiy** [comment]
@azbarcea how about https://github.com/Vestride/Shuffle ?
It seems to be active on GitHub if compare to quicksand
